# Wrapper Makefile for cross compiling piHPSDR with MinGW-w64
# It relies on the normal Makefile but overrides compiler and
# linker settings for the Windows toolchain.

include Makefile

override CC      := gcc
override LINK    := $(CC)
override PKG_CONFIG := pkg-config
override CFLAGS  += -mms-bitfields
override LDFLAGS += -mwindows
override SYSLIBS := -lwinpthread


